[features]
seeds = true
skip-lint = false

[programs.devnet]
aletheia = "ALETHX1A1111111111111111111111111111111111"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
