[features]
seeds = true
skip-lint = false

[programs.devnet]
aletheia = "GT5NYsctT5vnR6U1o45Jk28KREtjho6EApuAbaMrVK8g"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
